---
- name: installing Samba - Windows File sharing
  package: name=samba state=latest
  notify: startservicesamba
  
- name: Force all notified handlers to run at this point, not waiting for normal sync points
  meta: flush_handlers


