--- 
 - name: Install Cockpit-zfs manager
   git:
    repo: 'https://github.com/optimans/cockpit-zfs-manager.git'
    dest: /usr/share/cockpit
    clone: yes
   notify: startservicecockpit

 - name: Change Samba shares config to support Windows Shadow copy
   blockinfile:
     path: /etc/samba/smb.conf
     block: |
       [global]
       ~
       shadow: snapdir = .zfs/snapshot
       shadow: sort = desc
       shadow: format = %Y.%m.%d-%H.%M.%S
       shadow: localtime = yes	
       vfs objects = acl_xattr shadow_copy2
   notify: restartservicesamba
